/*9 Aug Database Patch*/
alter table potential add column description text;
alter table weapon_existence_data add column icon text;
alter table weapon_type add column shorthand text;
alter table weapon_existence_data add column special_name text;
alter table potential drop column description;
alter table potential_data add column description text;
alter table photon_art add column icon text;
alter table users add column recovery_hash text;
alter table armor rename column pb_gauge_build to slot;
alter table armor add column battle_power_value text;
CREATE TABLE "skill_tree_data"("id" SERIAL UNIQUE PRIMARY KEY,"class_id" int,"data" text,"skill_data" text,"line_color" text,"line_width" int,"gridsizex" int,"gridsizey" int,"gridpaddingx" int,"gridpaddingy" int);
ALTER TABLE "skill_tree_data" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("id");
alter table skill_tree_data add column halflineheight int;
CREATE TABLE "site_data" ("id" SERIAL UNIQUE PRIMARY KEY,"field" text,"data" text);
alter table class_skill_data alter column damage_taken set data type text;
alter table class_skill_data alter column pa_potency set data type text;
alter table class_skill_data alter column conditional_buff set data type text;
alter table class_skill_data alter column pp_recovery set data type text;
alter table class_skill_data alter column property set data type text;
alter table class_skill_data alter column all_damage_buff set data type text;
alter table class_skill_data alter column active_pp_recovery set data type text;
alter table class_skill_data alter column status_ailment_accum set data type text;
alter table class_skill_data alter column status_ailment_duration set data type text;
alter table class_skill_data alter column pp_consumption set data type text;
alter table class_skill_data alter column max_hp_decrease set data type text;
alter table class_skill_data alter column natural_pp_recovery set data type text;
alter table class_skill_data alter column pb_gauge_fortification set data type text;
alter table site_data rename column field to name;
alter table food add column description text;
alter table food add column icon text;